# Generated by Django 3.2.5 on 2021-08-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(default='Test title', max_length=64),
            preserve_default=False,
        ),
    ]
