# Generated by Django 3.2.5 on 2021-08-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='max_score',
            field=models.IntegerField(default=1),
        ),
    ]
