# Generated by Django 3.2.5 on 2021-08-25 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_question_max_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='testpart',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='test_part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tests.testpart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testpart',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_parts', to='tests.test'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answers',
            field=models.CharField(max_length=256),
        ),
        migrations.RemoveField(
            model_name='test',
            name='assigned_students',
        ),
        migrations.AddField(
            model_name='test',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, related_name='assigned_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='test',
            name='finished_students',
        ),
        migrations.AddField(
            model_name='test',
            name='finished_students',
            field=models.ManyToManyField(blank=True, related_name='finished_test', to=settings.AUTH_USER_MODEL),
        ),
    ]
