# Generated by Django 3.2.5 on 2021-08-25 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_auto_20210825_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpart',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_parts', to='tests.test'),
            preserve_default=False,
        ),
    ]
