# Generated by Django 3.2.5 on 2021-08-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_alter_testpart_content_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpart',
            name='content_img',
            field=models.ImageField(blank=True, upload_to='tests/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
