# Generated by Django 3.2.5 on 2021-08-25 17:04

from django.db import migrations, models
import tests.models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_alter_testpart_content_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpart',
            name='content_img',
            field=models.ImageField(blank=True, upload_to=tests.models.TestPart.get_upload_path),
        ),
    ]
