# Generated by Django 3.2.5 on 2021-08-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_alter_testpart_content_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
    ]
