# Generated by Django 3.2.5 on 2021-08-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_rename_title_testpart_part_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testpart',
            old_name='content',
            new_name='title',
        ),
    ]
