# Generated by Django 3.2.5 on 2021-08-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_rename_title_testpart_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpart',
            name='part_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
