# Generated by Django 3.2.5 on 2021-08-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_alter_testpart_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testpart',
            old_name='multiple_choice',
            new_name='is_multiple_choice',
        ),
    ]
