# Generated by Django 3.2.5 on 2021-08-27 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0022_rename_multiple_choice_testpart_is_multiple_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='test_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.testpart'),
        ),
    ]
