# Generated by Django 3.2.5 on 2021-08-27 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0023_alter_question_test_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
