# Generated by Django 3.2.5 on 2021-08-27 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0024_test_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('score_percent', models.DecimalField(decimal_places=1, max_digits=4)),
                ('finished_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='finished_students',
            field=models.ManyToManyField(blank=True, related_name='finished_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
        migrations.AddField(
            model_name='testassignment',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
