# Generated by Django 3.2.5 on 2021-08-27 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0028_auto_20210827_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_assignements', to=settings.AUTH_USER_MODEL),
        ),
    ]
