# Generated by Django 3.2.5 on 2021-08-27 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0030_alter_testassignment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='test_assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.testassignment'),
            preserve_default=False,
        ),
    ]
