# Generated by Django 3.2.5 on 2021-08-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0031_answer_test_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
