# Generated by Django 3.2.5 on 2021-08-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0032_alter_answer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True),
        ),
    ]
