# Generated by Django 3.2.5 on 2021-08-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0033_alter_answer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
