# Generated by Django 3.2.5 on 2021-08-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0034_user_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='assigned_students',
        ),
        migrations.RemoveField(
            model_name='test',
            name='finished_students',
        ),
    ]
