# Generated by Django 3.2.5 on 2021-08-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0035_auto_20210827_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='max_score',
        ),
        migrations.AddField(
            model_name='testpart',
            name='max_score_per_answer',
            field=models.IntegerField(default=1),
        ),
    ]
