# Generated by Django 3.2.5 on 2021-08-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0036_auto_20210827_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpart',
            name='max_score_per_answer',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
