# Generated by Django 3.2.5 on 2021-08-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0037_alter_testpart_max_score_per_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
    ]
