# Generated by Django 3.2.5 on 2021-08-30 08:56

from django.db import migrations, models
import tests.models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0038_remove_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, default=None, null=True, upload_to=tests.models.Question.get_upload_path),
        ),
        migrations.AddField(
            model_name='testpart',
            name='audio',
            field=models.FileField(blank=True, default=None, null=True, upload_to=tests.models.TestPart.get_upload_path),
        ),
    ]
