# Generated by Django 3.2.5 on 2021-09-01 09:59

from django.db import migrations, models
import tests.models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0039_auto_20210830_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpart',
            name='content_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=tests.models.TestPart.get_upload_path),
        ),
    ]
