# Generated by Django 3.2.5 on 2021-09-06 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0040_alter_testpart_content_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testassignment',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tests.test'),
        ),
    ]
